export default {
  patient: {
    resourceType: "Bundle",

    type: "transaction",

    meta: {
      lastUpdated: "2018-09-26T02:55:48.525Z",

      fhir_comments: ["Generated by FRED"]
    },

    entry: [
      {
        fullUrl: "Patient/trenton",

        request: {
          method: "PUT",

          url: "Patient/trenton"
        },

        resource: {
          resourceType: "Patient",

          id: "trenton",

          active: true,

          name: [
            {
              family: ["Burns"],

              given: ["Nathan"]
            }
          ],

          telecom: [
            {
              value: "044455790"
            }
          ],

          gender: "male",

          birthDate: "2000-04-20",

          deceasedBoolean: "false",

          address: [
            {
              line: ["67 Elm St"],

              city: "Barcaldine",

              state: "QLD",

              postalCode: "4725"
            }
          ],

          contact: [
            {
              relationship: [
                {
                  text: "Brother"
                }
              ],

              name: {
                family: ["Burns"],

                given: ["Darren"]
              },

              telecom: [
                {
                  value: "0433668188"
                }
              ],

              address: {
                line: ["67 Elm St"],

                city: "Barcaldine",

                state: "QLD",

                postalCode: "4725"
              }
            }
          ]
        }
      },

      {
        fullUrl: "Condition/MEDI7212-15-smoking",

        request: {
          method: "PUT",

          url: "Condition/MEDI7212-15-smoking"
        },

        resource: {
          resourceType: "Condition",

          id: "MEDI7212-15-smoking",

          patient: {
            id: "MEDI7212-15-patient"
          },

          code: {
            coding: [
              {
                system: "http://snomed.info/sct",

                code: "77176002",

                display: "Smoker"
              }
            ]
          },

          verificationStatus: "confirmed"
        }
      },

      {
        fullUrl: "Condition/MEDI7212-15-pastburn",

        request: {
          method: "PUT",

          url: "Condition/MEDI7212-15-pastburn"
        },

        resource: {
          resourceType: "Condition",

          id: "MEDI7212-15-pastburn",

          patient: {
            id: "MEDI7212-15-patient"
          },

          code: {
            coding: [
              {
                system: "http://snomed.info/sct",

                code: "276468004",

                display: "Cigarette burn"
              }
            ]
          },

          verificationStatus: "confirmed"
        }
      },

      {
        fullUrl: "Condition/MEDI7212-15-drinking",

        request: {
          method: "PUT",

          url: "Condition/MEDI7212-15-drinking"
        },

        resource: {
          resourceType: "Condition",

          id: "MEDI7212-15-drinking",

          patient: {
            id: "MEDI7212-15-patient"
          },

          code: {
            coding: [
              {
                system: "http://snomed.info/sct",

                code: "43783005",

                display: "Moderate drinker"
              }
            ]
          },

          verificationStatus: "confirmed"
        }
      },

      {
        fullUrl: "Condition/MEDI7212-15-weed",

        request: {
          method: "PUT",

          url: "Condition/MEDI7212-15-weed"
        },

        resource: {
          resourceType: "Condition",

          id: "MEDI7212-15-weed",

          patient: {
            id: "MEDI7212-15-patient"
          },

          code: {
            coding: [
              {
                system: "http://snomed.info/sct",

                code: "733460004",

                display: "Marijuana user"
              }
            ]
          },

          verificationStatus: "confirmed"
        }
      },

      {
        fullUrl: "Immunization/MEDI7212-15-booster",

        request: {
          method: "PUT",

          url: "Immunization/MEDI7212-15-booster"
        },

        resource: {
          resourceType: "Immunization",

          id: "MEDI7212-15-booster",

          status: "completed",

          date: "2015",

          vaccineCode: {
            coding: [
              {
                system: "http://hl7.org/fhir/sid/cvx",

                code: "112",

                display: "tetanus toxoid, unspecified formulation"
              }
            ]
          },

          patient: {
            id: "MEDI7212-15-patient"
          },

          wasNotGiven: true,

          reported: true
        }
      }
    ]
  }
};
